<!DOCTYPE html>

<html lang="es">

	<head>
		<meta charset="UTF-8">
		<title>Error 404</title>
		<link href="<?php echo Routing::base_url(); ?>public/css/error.css" rel="stylesheet" type="text/css">

	</head>

	<body>
		<div class="figure">
			<img src="<?php echo Routing::base_url(); ?>public/img/error.png" alt="Error:">
		</div>

		<div id="errorbox">
			<h1>Error (404)</h1> Disculpas! la página que buscas no se puede encontrar.
			
			<p><a href="<?php echo Routing::base_url(); ?>">Salir de aquí.</a></p>
		</div>


		</body>
</html>


